Repository ivandi1980/my-nestpro, pull requests merged in 2023-03, with the labels that each got.

#1 code cleanup
  .env
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
Labels: documentation, enhancement

#3 readme updated!
  README.md
  assets/get_all_users.png
  src/app.module.ts
  src/users/controller/users/users.controller.spec.ts
  src/users/controller/users/users.controller.ts
  src/users/users.module.ts
Labels: documentation, enhancement

#4 README updated!
  README.md
Labels: documentation, enhancement

#5 Controller & README updated!
  README.md
  assets/get_all_users_posts.png
  src/users/controller/users/users.controller.ts
Labels: documentation, enhancement

#6 fixed: can't resolve ConfigService
  README.md
  src/app.module.ts
  src/main.ts
  src/users/users.module.ts
Labels: bug, enhancement

#7 add query params
  src/users/controller/users/users.controller.ts
  src/users/dtos/CreateUser.dto.ts
Labels: enhancement

#9 add service layer
  src/users/controller/users/users.controller.ts
  src/users/services/users/users.service.spec.ts
  src/users/services/users/users.service.ts
  src/users/users.module.ts
  src/utils/types.ts
Labels: enhancement

#11 remove env
  .env
Labels: bug, enhancement

#12 Swagger added!
  README.md
  assets/swagger.png
  package-lock.json
  package.json
  src/main.ts
Labels: documentation, enhancement

#13 Dockerfile added!
  .dockerignore
  Dockerfile
  README.md
Labels: documentation, enhancement

#14 Dockerfile updated!
  .dockerignore
  Dockerfile
  README.md
Labels: bug, documentation, enhancement

#15 pipes added!
  README.md
  src/users/controller/users/users.controller.ts
  src/users/dtos/CreateUser.dto.ts
  src/users/pipes/validate-create-user/validate-create-user.pipe.spec.ts
  src/users/pipes/validate-create-user/validate-create-user.pipe.ts
  src/users/services/users/users.service.ts
Labels: bug, documentation

#16 update pipes!
  src/users/pipes/validate-create-user/validate-create-user.pipe.ts
Labels: bug
